-- Leader_Grey
-- Author: wldcmzy
-- DateCreated: 2/27/2024 8:09:45 PM
--------------------------------------------------------------
INSERT INTO Types	
(Type,														Kind)
VALUES
('LEADER_STELLARIS_GREY',									'KIND_LEADER'),
('TRAIT_LEADER_STELLARIS_GREY',								'KIND_TRAIT'),
('MODIFIERTYPE_PLAYER_CITY_ADJUST_CITY_YIELD_STELLARIS',	'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
(ModifierType,												CollectionType,					EffectType) 
VALUES 
('MODIFIERTYPE_PLAYER_CITY_ADJUST_CITY_YIELD_STELLARIS',	'COLLECTION_PLAYER_CITIES',		'EFFECT_ADJUST_CITY_YIELD_MODIFIER');

INSERT INTO Traits				
(TraitType,								Name,										Description)
VALUES
('TRAIT_LEADER_STELLARIS_GREY',			'LOC_TRAIT_LEADER_STELLARIS_GREY_NAME',		'LOC_TRAIT_LEADER_STELLARIS_GREY_DESCRIPTION');

INSERT INTO Leaders			
(LeaderType,					Name,									InheritFrom,		SceneLayers)
VALUES
('LEADER_STELLARIS_GREY',		'LOC_LEADER_STELLARIS_GREY_NAME',		'LEADER_DEFAULT',	'4');

INSERT INTO LeaderTraits	
(LeaderType,					TraitType)
VALUES
('LEADER_STELLARIS_GREY',	'TRAIT_LEADER_STELLARIS_GREY');

INSERT INTO LeaderQuotes
(LeaderType,					Quote)
VALUES
('LEADER_STELLARIS_GREY',	'LOC_PEDIA_LEADERS_PAGE_LEADER_STELLARIS_GREY_QUOTE');


INSERT INTO TraitModifiers 
(TraitType,							ModifierId) 
VALUES 
('TRAIT_LEADER_STELLARIS_GREY',		'MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF'),
('TRAIT_LEADER_STELLARIS_GREY',		'MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF_INFO_ERA'),
('TRAIT_LEADER_STELLARIS_GREY',		'MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_GRANT_SCIENCE_ROBOT'),
('TRAIT_LEADER_STELLARIS_GREY',		'MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_GRANT_SCIENCE_NANO'),
('TRAIT_LEADER_STELLARIS_GREY',		'MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_ADJACENCY'),
('TRAIT_LEADER_STELLARIS_GREY',		'MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_PRODUCTION');




INSERT INTO Modifiers 
(ModifierId,														ModifierType,												RunOnce,	Permanent,	NewOnly,	OwnerRequirementSetId,	SubjectRequirementSetId) 
VALUES 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF',			'MODIFIERTYPE_PLAYER_CITY_ADJUST_CITY_YIELD_STELLARIS',		0,			0,			0,			NULL,					NULL),	
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF_INFO_ERA', 'MODIFIERTYPE_PLAYER_CITY_ADJUST_CITY_YIELD_STELLARIS',		0,			0,			0,			NULL,					'REQSET_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_GRANT_SCIENCE_ROBOT',	'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',				0,			0,			0,			NULL,					'REQSET_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_GRANT_SCIENCE_NANO',	'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',				0,			0,			0,			NULL,					'REQSET_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_ADJACENCY',			'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',				0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_PRODUCTION',			'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 0,	0,			0,			NULL,					NULL);



INSERT INTO ModifierArguments 
(ModifierId,														Name,					Value) 
VALUES 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF',			'Amount',				'10'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF',			'YieldType',			'YIELD_SCIENCE'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF_INFO_ERA', 'Amount',				'40'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_SCIENCE_BUFF_INFO_ERA', 'YieldType',			'YIELD_SCIENCE'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_GRANT_SCIENCE_ROBOT',	'TechType',				'TECH_ROBOTICS'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_CITY_GRANT_SCIENCE_NANO',	'TechType',				'TECH_NANOTECHNOLOGY'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_ADJACENCY',			'Amount',				'1'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_ADJACENCY',			'Description',			'LOC_DISTRICT_DISTRICT_1_SCIENCE'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_ADJACENCY',			'DistrictType',			'DISTRICT_CAMPUS'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_ADJACENCY',			'YieldType',			'YIELD_SCIENCE'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_PRODUCTION',			'DistrictType',			'DISTRICT_CAMPUS'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_PRODUCTION',			'YieldTypeToGrant',		'YIELD_PRODUCTION'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_COMPUS_PRODUCTION',			'YieldTypeToMirror',	'YIELD_SCIENCE');




INSERT INTO RequirementSets 
(RequirementSetId,											RequirementSetType) 
VALUES 
('REQSET_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA',	'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements 
(RequirementSetId,											RequirementId) 
VALUES 
('REQSET_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA',	'REQ_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA');


INSERT INTO Requirements 
(RequirementId,											RequirementType) 
VALUES 
('REQ_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA',	'REQUIREMENT_PLAYER_ERA_AT_LEAST');

INSERT INTO RequirementArguments 
(RequirementId,											Name,		Value) 
VALUES 
('REQ_TRAIT_LEADER_STELLARIS_GREY_IS_AFTER_INFO_ERA',	'EraType',	'ERA_INFORMATION');











INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_AI_BUFF', 'MODIFIERTYPE_PLAYER_CITY_ADJUST_CITY_YIELD_STELLARIS', 0, 0, 0, NULL, NULL),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_AI_BUFF2', 'MODIFIERTYPE_PLAYER_CITY_ADJUST_CITY_YIELD_STELLARIS', 0, 0, 0, NULL, NULL);


INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_AI_BUFF', 'Amount', '18'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_AI_BUFF', 'YieldType', 'YIELD_SCIENCE'),
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_AI_BUFF2', 'Amount', '12'), 
('MODIFIER_TRAIT_LEADER_STELLARIS_GREY_AI_BUFF2', 'YieldType', 'YIELD_PRODUCTION');
