-- Config
-- Author: wldcmzy
-- DateCreated: 2/24/2024 11:20:47 PM
--------------------------------------------------------------

INSERT INTO Players	
(Domain,						CivilizationType,					LeaderType,						CivilizationName,							CivilizationIcon,						LeaderName,								LeaderIcon,							CivilizationAbilityName,							CivilizationAbilityDescription,							CivilizationAbilityIcon,					LeaderAbilityName,								LeaderAbilityDescription,							LeaderAbilityIcon,					Portrait,											PortraitBackground)		
VALUES
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ZOEY_3',		'LOC_CIVILIZATION_ORIGINALSTELLARIS_NAME',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',	'LOC_LEADER_STELLARIS_ZOEY_3_NAME',		'ICON_LEADER_STELLARIS_ZOEY_3',		'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_NAME',		'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_DESCRIPTION',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',		'LOC_TRAIT_LEADER_STELLARIS_ZOEY_3_NAME',		'LOC_TRAIT_LEADER_STELLARIS_ZOEY_3_DESCRIPTION',	'ICON_LEADER_STELLARIS_ZOEY_3',		NULL,												NULL),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_WITCH_6',		'LOC_CIVILIZATION_ORIGINALSTELLARIS_NAME',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',	'LOC_LEADER_STELLARIS_WITCH_6_NAME',	'ICON_LEADER_STELLARIS_WITCH_6',	'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_NAME',		'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_DESCRIPTION',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',		'LOC_TRAIT_LEADER_STELLARIS_WITCH_6_NAME',		'LOC_TRAIT_LEADER_STELLARIS_WITCH_6_DESCRIPTION',	'ICON_LEADER_STELLARIS_WITCH_6',	NULL,												NULL),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ELLIS_5',		'LOC_CIVILIZATION_ORIGINALSTELLARIS_NAME',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',	'LOC_LEADER_STELLARIS_ELLIS_5_NAME',	'ICON_LEADER_STELLARIS_ELLIS_5',	'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_NAME',		'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_DESCRIPTION',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',		'LOC_TRAIT_LEADER_STELLARIS_ELLIS_5_NAME',		'LOC_TRAIT_LEADER_STELLARIS_ELLIS_5_DESCRIPTION',	'ICON_LEADER_STELLARIS_ELLIS_5',	NULL,												NULL),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_GREY',		'LOC_CIVILIZATION_ORIGINALSTELLARIS_NAME',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',	'LOC_LEADER_STELLARIS_GREY_NAME',		'ICON_LEADER_STELLARIS_GREY',		'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_NAME',		'LOC_TRAIT_CIVILIZATION_ORIGINALSTELLARIS_DESCRIPTION',	'ICON_CIVILIZATION_ORIGINALSTELLARIS',		'LOC_TRAIT_LEADER_STELLARIS_GREY_NAME',			'LOC_TRAIT_LEADER_STELLARIS_GREY_DESCRIPTION',		'ICON_LEADER_STELLARIS_GREY',		'IMG_LEADER_STELLARIS_GREY_FOREGROUND_.dds',		NULL);



INSERT INTO PlayerItems
(Domain,						CivilizationType,					LeaderType,						Type,							Icon,								Name,									Description,									SortIndex)
VALUES
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_GREY',		'PROJECT_BECOME_THE_CRISIS',	'ICON_PROJECT_BECOME_THE_CRISIS',	'LOC_PROJECT_BECOME_THE_CRISIS_NAME',	'LOC_PROJECT_BECOME_THE_CRISIS_DESCRIPTION',	50),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_WITCH_6',		'PROJECT_BECOME_THE_CRISIS',	'ICON_PROJECT_BECOME_THE_CRISIS',	'LOC_PROJECT_BECOME_THE_CRISIS_NAME',	'LOC_PROJECT_BECOME_THE_CRISIS_DESCRIPTION',	50),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ZOEY_3',		'PROJECT_BECOME_THE_CRISIS',	'ICON_PROJECT_BECOME_THE_CRISIS',	'LOC_PROJECT_BECOME_THE_CRISIS_NAME',	'LOC_PROJECT_BECOME_THE_CRISIS_DESCRIPTION',	50),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_GREY',		'PROJECT_LOSSUS_PROJECT',		'ICON_PROJECT_LOSSUS_PROJECT',		'LOC_PROJECT_LOSSUS_PROJECT_NAME',		'LOC_PROJECT_LOSSUS_PROJECT_DESCRIPTION',		51),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_WITCH_6',		'PROJECT_LOSSUS_PROJECT',		'ICON_PROJECT_LOSSUS_PROJECT',		'LOC_PROJECT_LOSSUS_PROJECT_NAME',		'LOC_PROJECT_LOSSUS_PROJECT_DESCRIPTION',		51),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ZOEY_3',		'PROJECT_LOSSUS_PROJECT',		'ICON_PROJECT_LOSSUS_PROJECT',		'LOC_PROJECT_LOSSUS_PROJECT_NAME',		'LOC_PROJECT_LOSSUS_PROJECT_DESCRIPTION',		51),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ELLIS_5',		'PROJECT_LOSSUS_PROJECT',		'ICON_PROJECT_LOSSUS_PROJECT',		'LOC_PROJECT_LOSSUS_PROJECT_NAME',		'LOC_PROJECT_LOSSUS_PROJECT_DESCRIPTION',		51),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_GREY',		'PROJECT_ONE_VOICE_RULES',		'ICON_PROJECT_ONE_VOICE_RULES',		'LOC_PROJECT_ONE_VOICE_RULES_NAME',		'LOC_PROJECT_ONE_VOICE_RULES_DESCRIPTION',		52),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ZOEY_3',		'PROJECT_ONE_VOICE_RULES',		'ICON_PROJECT_ONE_VOICE_RULES',		'LOC_PROJECT_ONE_VOICE_RULES_NAME',		'LOC_PROJECT_ONE_VOICE_RULES_DESCRIPTION',		52),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ELLIS_5',		'PROJECT_ONE_VOICE_RULES',		'ICON_PROJECT_ONE_VOICE_RULES',		'LOC_PROJECT_ONE_VOICE_RULES_NAME',		'LOC_PROJECT_ONE_VOICE_RULES_DESCRIPTION',		52),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_ELLIS_5',		'PROJECT_YYWHZGTZM',			'ICON_PROJECT_YYWHZGTZM',			'LOC_PROJECT_YYWHZGTZM_NAME',			'LOC_PROJECT_YYWHZGTZM_DESCRIPTION',			55),
('Players:Expansion2_Players',	'CIVILIZATION_ORIGINALSTELLARIS',	'LEADER_STELLARIS_WITCH_6',		'BUILDING_OFFSPRING_NEST',		'ICON_BUILDING_OFFSPRING_NEST',		'LOC_BUILDING_OFFSPRING_NEST_NAME',		'LOC_BUILDING_OFFSPRING_NEST_DESCRIPTION',		30);
